ci:
  collect:
    url:
      - http://localhost:3000
      - http://localhost:3000/blog
      - http://localhost:3000/portfolio
      - http://localhost:3000/about
    startServerCommand: npm run start
    startServerReadyPattern: ready on
    startServerReadyTimeout: 30000
    numberOfRuns: 3
  assert:
    assertions:
      'categories:performance': ['error', {'minScore': 0.8}]
      'categories:accessibility': ['error', {'minScore': 0.9}]
      'categories:best-practices': ['error', {'minScore': 0.8}]
      'categories:seo': ['error', {'minScore': 0.9}]
      'first-contentful-paint': ['error', {'maxNumericValue': 2000}]
      'largest-contentful-paint': ['error', {'maxNumericValue': 4000}]
      'cumulative-layout-shift': ['error', {'maxNumericValue': 0.1}]
      'total-blocking-time': ['error', {'maxNumericValue': 300}]
  upload:
    target: 'temporary-public-storage' 