global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Next.js Application
  - job_name: 'matt-dinh-blog'
    static_configs:
      - targets: ['app:3000']
    metrics_path: '/api/metrics'
    scrape_interval: 30s

  # Node Exporter (if running)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  # PostgreSQL (if using local)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    profiles:
      - local-db

  # MinIO (if using local)
  - job_name: 'minio'
    static_configs:
      - targets: ['minio:9000']
    profiles:
      - local-storage

  # Nginx (if using)
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    profiles:
      - production

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093 