-- Add more sample blog posts for homepage testing
-- This script adds 8 more posts to ensure we have enough for pagination

-- Insert additional blog posts
INSERT INTO blog_posts (slug, status, published_at, thumbnail_url, created_at, updated_at) VALUES
('ai-machine-learning-basics', 'published', '2025-06-28T10:00:00Z', 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&h=400&fit=crop', NOW(), NOW()),
('web-development-trends-2025', 'published', '2025-06-27T14:30:00Z', 'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=800&h=400&fit=crop', NOW(), NOW()),
('productivity-tips-for-developers', 'published', '2025-06-26T09:15:00Z', 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?w=800&h=400&fit=crop', NOW(), NOW()),
('remote-work-best-practices', 'published', '2025-06-25T16:45:00Z', 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=800&h=400&fit=crop', NOW(), NOW()),
('typescript-advanced-patterns', 'published', '2025-06-24T11:20:00Z', 'https://images.unsplash.com/photo-1516116216624-53e697fedbea?w=800&h=400&fit=crop', NOW(), NOW()),
('database-design-principles', 'published', '2025-06-23T13:10:00Z', 'https://images.unsplash.com/photo-1544383835-bda2bc66a55d?w=800&h=400&fit=crop', NOW(), NOW()),
('cloud-computing-fundamentals', 'published', '2025-06-22T08:30:00Z', 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&h=400&fit=crop', NOW(), NOW()),
('cybersecurity-basics', 'published', '2025-06-21T15:45:00Z', 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&h=400&fit=crop', NOW(), NOW())
ON CONFLICT (slug) DO NOTHING;

-- Insert English translations for the new posts
INSERT INTO blog_post_translations (blog_post_id, language_code, title, summary, content, created_at, updated_at) VALUES
((SELECT id FROM blog_posts WHERE slug = 'ai-machine-learning-basics'), 'en', 'AI and Machine Learning Basics', 'An introduction to artificial intelligence and machine learning concepts for beginners.', '<h1>AI and Machine Learning Basics</h1><p>Artificial Intelligence (AI) and Machine Learning (ML) are transforming the way we live and work.</p><h2>What is AI?</h2><p>AI refers to the simulation of human intelligence in machines that are programmed to think and learn like humans.</p><h2>Machine Learning Fundamentals</h2><p>Machine Learning is a subset of AI that enables computers to learn and improve from experience without being explicitly programmed.</p>', NOW(), NOW()),
((SELECT id FROM blog_posts WHERE slug = 'web-development-trends-2025'), 'en', 'Web Development Trends in 2025', 'Explore the latest trends and technologies shaping the future of web development.', '<h1>Web Development Trends in 2025</h1><p>The web development landscape is constantly evolving with new technologies and frameworks emerging every year.</p><h2>Key Trends</h2><ul><li>Serverless Architecture</li><li>Progressive Web Apps (PWAs)</li><li>AI-Powered Development Tools</li><li>WebAssembly</li></ul>', NOW(), NOW()),
((SELECT id FROM blog_posts WHERE slug = 'productivity-tips-for-developers'), 'en', 'Productivity Tips for Developers', 'Boost your coding productivity with these proven techniques and tools.', '<h1>Productivity Tips for Developers</h1><p>Being productive as a developer requires more than just coding skills.</p><h2>Essential Tips</h2><ul><li>Use keyboard shortcuts</li><li>Automate repetitive tasks</li><li>Take regular breaks</li><li>Stay organized</li></ul>', NOW(), NOW()),
((SELECT id FROM blog_posts WHERE slug = 'remote-work-best-practices'), 'en', 'Remote Work Best Practices', 'Master the art of working remotely with these essential practices and tools.', '<h1>Remote Work Best Practices</h1><p>Remote work has become the new normal for many professionals worldwide.</p><h2>Best Practices</h2><ul><li>Set up a dedicated workspace</li><li>Establish clear boundaries</li><li>Use collaboration tools</li><li>Maintain regular communication</li></ul>', NOW(), NOW()),
((SELECT id FROM blog_posts WHERE slug = 'typescript-advanced-patterns'), 'en', 'Advanced TypeScript Patterns', 'Learn advanced TypeScript patterns and techniques for better code quality.', '<h1>Advanced TypeScript Patterns</h1><p>TypeScript offers powerful features that can significantly improve your code quality and developer experience.</p><h2>Advanced Patterns</h2><ul><li>Generic Types</li><li>Conditional Types</li><li>Utility Types</li><li>Decorators</li></ul>', NOW(), NOW()),
((SELECT id FROM blog_posts WHERE slug = 'database-design-principles'), 'en', 'Database Design Principles', 'Master the fundamentals of database design for scalable and efficient applications.', '<h1>Database Design Principles</h1><p>Good database design is crucial for building scalable and maintainable applications.</p><h2>Key Principles</h2><ul><li>Normalization</li><li>Data Integrity</li><li>Performance Optimization</li><li>Security</li></ul>', NOW(), NOW()),
((SELECT id FROM blog_posts WHERE slug = 'cloud-computing-fundamentals'), 'en', 'Cloud Computing Fundamentals', 'Understand the basics of cloud computing and its impact on modern software development.', '<h1>Cloud Computing Fundamentals</h1><p>Cloud computing has revolutionized how we build and deploy applications.</p><h2>Cloud Models</h2><ul><li>Infrastructure as a Service (IaaS)</li><li>Platform as a Service (PaaS)</li><li>Software as a Service (SaaS)</li></ul>', NOW(), NOW()),
((SELECT id FROM blog_posts WHERE slug = 'cybersecurity-basics'), 'en', 'Cybersecurity Basics for Developers', 'Essential cybersecurity knowledge every developer should have.', '<h1>Cybersecurity Basics for Developers</h1><p>Security should be a top priority for every developer, regardless of their specialization.</p><h2>Security Fundamentals</h2><ul><li>Input Validation</li><li>Authentication & Authorization</li><li>Data Encryption</li><li>Secure Communication</li></ul>', NOW(), NOW())
ON CONFLICT (blog_post_id, language_code) DO NOTHING;

-- Insert Vietnamese translations for the new posts
INSERT INTO blog_post_translations (blog_post_id, language_code, title, summary, content, created_at, updated_at) VALUES
((SELECT id FROM blog_posts WHERE slug = 'ai-machine-learning-basics'), 'vi', 'Cơ Bản Về AI và Machine Learning', 'Giới thiệu về trí tuệ nhân tạo và các khái niệm machine learning cho người mới bắt đầu.', '<h1>Cơ Bản Về AI và Machine Learning</h1><p>Trí tuệ nhân tạo (AI) và Machine Learning (ML) đang thay đổi cách chúng ta sống và làm việc.</p><h2>AI là gì?</h2><p>AI đề cập đến việc mô phỏng trí thông minh của con người trong máy móc được lập trình để suy nghĩ và học hỏi như con người.</p><h2>Nền Tảng Machine Learning</h2><p>Machine Learning là một tập con của AI cho phép máy tính học và cải thiện từ kinh nghiệm mà không cần được lập trình rõ ràng.</p>', NOW(), NOW()),
((SELECT id FROM blog_posts WHERE slug = 'web-development-trends-2025'), 'vi', 'Xu Hướng Phát Triển Web Năm 2025', 'Khám phá những xu hướng và công nghệ mới nhất định hình tương lai của phát triển web.', '<h1>Xu Hướng Phát Triển Web Năm 2025</h1><p>Lĩnh vực phát triển web liên tục phát triển với các công nghệ và framework mới xuất hiện mỗi năm.</p><h2>Xu Hướng Chính</h2><ul><li>Kiến Trúc Serverless</li><li>Ứng Dụng Web Tiến Bộ (PWAs)</li><li>Công Cụ Phát Triển Được Hỗ Trợ AI</li><li>WebAssembly</li></ul>', NOW(), NOW()),
((SELECT id FROM blog_posts WHERE slug = 'productivity-tips-for-developers'), 'vi', 'Mẹo Tăng Năng Suất Cho Lập Trình Viên', 'Tăng năng suất lập trình với những kỹ thuật và công cụ đã được chứng minh.', '<h1>Mẹo Tăng Năng Suất Cho Lập Trình Viên</h1><p>Để có năng suất cao với tư cách là lập trình viên cần nhiều hơn là chỉ kỹ năng lập trình.</p><h2>Mẹo Quan Trọng</h2><ul><li>Sử dụng phím tắt</li><li>Tự động hóa các tác vụ lặp lại</li><li>Nghỉ giải lao thường xuyên</li><li>Giữ tổ chức</li></ul>', NOW(), NOW()),
((SELECT id FROM blog_posts WHERE slug = 'remote-work-best-practices'), 'vi', 'Thực Hành Tốt Nhất Cho Làm Việc Từ Xa', 'Làm chủ nghệ thuật làm việc từ xa với những thực hành và công cụ thiết yếu.', '<h1>Thực Hành Tốt Nhất Cho Làm Việc Từ Xa</h1><p>Làm việc từ xa đã trở thành bình thường mới cho nhiều chuyên gia trên toàn thế giới.</p><h2>Thực Hành Tốt Nhất</h2><ul><li>Thiết lập không gian làm việc riêng</li><li>Thiết lập ranh giới rõ ràng</li><li>Sử dụng công cụ hợp tác</li><li>Duy trì giao tiếp thường xuyên</li></ul>', NOW(), NOW()),
((SELECT id FROM blog_posts WHERE slug = 'typescript-advanced-patterns'), 'vi', 'Mẫu TypeScript Nâng Cao', 'Học các mẫu và kỹ thuật TypeScript nâng cao để có chất lượng code tốt hơn.', '<h1>Mẫu TypeScript Nâng Cao</h1><p>TypeScript cung cấp các tính năng mạnh mẽ có thể cải thiện đáng kể chất lượng code và trải nghiệm developer.</p><h2>Mẫu Nâng Cao</h2><ul><li>Generic Types</li><li>Conditional Types</li><li>Utility Types</li><li>Decorators</li></ul>', NOW(), NOW()),
((SELECT id FROM blog_posts WHERE slug = 'database-design-principles'), 'vi', 'Nguyên Tắc Thiết Kế Cơ Sở Dữ Liệu', 'Làm chủ những nguyên tắc cơ bản của thiết kế cơ sở dữ liệu cho các ứng dụng có thể mở rộng và hiệu quả.', '<h1>Nguyên Tắc Thiết Kế Cơ Sở Dữ Liệu</h1><p>Thiết kế cơ sở dữ liệu tốt rất quan trọng để xây dựng các ứng dụng có thể mở rộng và bảo trì.</p><h2>Nguyên Tắc Chính</h2><ul><li>Chuẩn Hóa</li><li>Tính Toàn Vẹn Dữ Liệu</li><li>Tối Ưu Hóa Hiệu Suất</li><li>Bảo Mật</li></ul>', NOW(), NOW()),
((SELECT id FROM blog_posts WHERE slug = 'cloud-computing-fundamentals'), 'vi', 'Nền Tảng Điện Toán Đám Mây', 'Hiểu những cơ bản của điện toán đám mây và tác động của nó đối với phát triển phần mềm hiện đại.', '<h1>Nền Tảng Điện Toán Đám Mây</h1><p>Điện toán đám mây đã cách mạng hóa cách chúng ta xây dựng và triển khai ứng dụng.</p><h2>Mô Hình Đám Mây</h2><ul><li>Infrastructure as a Service (IaaS)</li><li>Platform as a Service (PaaS)</li><li>Software as a Service (SaaS)</li></ul>', NOW(), NOW()),
((SELECT id FROM blog_posts WHERE slug = 'cybersecurity-basics'), 'vi', 'Cơ Bản Bảo Mật Mạng Cho Lập Trình Viên', 'Kiến thức bảo mật mạng thiết yếu mà mọi lập trình viên nên có.', '<h1>Cơ Bản Bảo Mật Mạng Cho Lập Trình Viên</h1><p>Bảo mật nên là ưu tiên hàng đầu cho mọi lập trình viên, bất kể chuyên môn của họ.</p><h2>Nền Tảng Bảo Mật</h2><ul><li>Xác Thực Đầu Vào</li><li>Xác Thực & Phân Quyền</li><li>Mã Hóa Dữ Liệu</li><li>Giao Tiếp An Toàn</li></ul>', NOW(), NOW())
ON CONFLICT (blog_post_id, language_code) DO NOTHING;

-- Display the results
SELECT 'Added sample posts successfully!' as message;
SELECT COUNT(*) as total_posts FROM blog_posts WHERE status = 'published';
SELECT COUNT(*) as total_translations FROM blog_post_translations; 